  
on:
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]
jobs:
 test:
  name: Run test
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@master
  - uses: mr-smithers-excellent/docker-build-push@v5
    name: Build & push Docker image
    with:
      image: hassandocker510
      tags: v1, firts
      registry: docker.io
      dockerfile: Dockerfile
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
